//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheepNumberPlace_Cs.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SheepNumberPlace_Cs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap AnswerCheck {
            get {
                object obj = ResourceManager.GetObject("AnswerCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_l {
            get {
                object obj = ResourceManager.GetObject("arrow_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_ld {
            get {
                object obj = ResourceManager.GetObject("arrow_ld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_r {
            get {
                object obj = ResourceManager.GetObject("arrow_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_rd {
            get {
                object obj = ResourceManager.GetObject("arrow_rd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap batsu {
            get {
                object obj = ResourceManager.GetObject("batsu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap failure {
            get {
                object obj = ResourceManager.GetObject("failure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap hint {
            get {
                object obj = ResourceManager.GetObject("hint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap maru {
            get {
                object obj = ResourceManager.GetObject("maru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NewQ {
            get {
                object obj = ResourceManager.GetObject("NewQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   232
        ///****** No.0001 ******
        ///030009000
        ///000000407
        ///090170308
        ///000380001
        ///005000200
        ///300067000
        ///602053080
        ///704000000
        ///000600010
        ///****** No.0002 ******
        ///000270000
        ///000080052
        ///620000408
        ///004900005
        ///005000700
        ///200003900
        ///308000016
        ///760010000
        ///000048000
        ///****** No.0003 ******
        ///080000976
        ///000508000
        ///200900500
        ///003010000
        ///047000190
        ///000080600
        ///009006005
        ///000703000
        ///621000030
        ///****** No.0004 ******
        ///030090000
        ///710004000
        ///000160305
        ///000000108
        ///400309002
        ///506000000
        ///309081000
        ///000700049
        ///000040010
        ///****** No.0005 **** [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumLgLv3 {
            get {
                return ResourceManager.GetString("NumLgLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   345
        ///****** No.0001 ******
        ///000010080
        ///604000030
        ///050403010
        ///001900200
        ///009000500
        ///003008100
        ///080109020
        ///040000907
        ///030050000
        ///****** No.0002 ******
        ///700000042
        ///300000800
        ///004107000
        ///000030409
        ///009080700
        ///208050000
        ///000902500
        ///007000008
        ///920000003
        ///****** No.0003 ******
        ///000000041
        ///000187000
        ///960003000
        ///000600302
        ///007030900
        ///304002000
        ///000800029
        ///000396000
        ///150000000
        ///****** No.0004 ******
        ///000000209
        ///010200007
        ///060500400
        ///002040800
        ///400090001
        ///001050600
        ///008007020
        ///900005070
        ///304000000
        ///****** No.0005 **** [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumLgLv4 {
            get {
                return ResourceManager.GetString("NumLgLv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   171
        ///****** No.0001 ******
        ///000807040
        ///890400000
        ///000005030
        ///307020000
        ///009000100
        ///000050806
        ///050200000
        ///000003019
        ///040508000
        ///****** No.0002 ******
        ///910000000
        ///000103007
        ///000000650
        ///054010006
        ///001070200
        ///800030190
        ///032000000
        ///500608000
        ///000000074
        ///****** No.0003 ******
        ///060020000
        ///000004506
        ///010800000
        ///300000008
        ///709103402
        ///800000009
        ///000001030
        ///904700000
        ///000030020
        ///****** No.0004 ******
        ///000098010
        ///025000000
        ///000000074
        ///050809200
        ///100000005
        ///008107090
        ///510000000
        ///000000960
        ///090260000
        ///****** No.0005 **** [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumLgLv5 {
            get {
                return ResourceManager.GetString("NumLgLv5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   88
        ///****** No.0001 ******
        ///000000209
        ///007603000
        ///003008000
        ///040090080
        ///010402050
        ///030080060
        ///000100700
        ///000805600
        ///509000000
        ///****** No.0002 ******
        ///010040005
        ///000710800
        ///030000604
        ///905000000
        ///000402000
        ///000000706
        ///706000050
        ///008059000
        ///100080030
        ///****** No.0003 ******
        ///000750080
        ///040000000
        ///002006309
        ///800600000
        ///607000403
        ///000009005
        ///203800600
        ///000000090
        ///050017000
        ///****** No.0004 ******
        ///000802000
        ///000000005
        ///012006008
        ///039020070
        ///000030000
        ///050010860
        ///600300920
        ///400000000
        ///000501000
        ///****** No.0005 ***** [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumLgLv6 {
            get {
                return ResourceManager.GetString("NumLgLv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   24
        ///****** No.0001 ******
        ///050007800
        ///370000600
        ///000009000
        ///000012030
        ///700000008
        ///080750000
        ///000400000
        ///009000026
        ///004500090
        ///****** No.0002 ******
        ///079005000
        ///000408020
        ///000000400
        ///002060005
        ///801000609
        ///500010200
        ///003000000
        ///080704000
        ///000600810
        ///****** No.0003 ******
        ///028050000
        ///000006120
        ///007000000
        ///000600007
        ///250309084
        ///600002000
        ///000000900
        ///046800000
        ///000040830
        ///****** No.0004 ******
        ///300060000
        ///000800090
        ///210000000
        ///005701020
        ///002000300
        ///090405700
        ///000000061
        ///050009000
        ///000010002
        ///****** No.0005 ***** [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumLgLv7 {
            get {
                return ResourceManager.GetString("NumLgLv7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap openfile {
            get {
                object obj = ResourceManager.GetObject("openfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Reset {
            get {
                object obj = ResourceManager.GetObject("Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ResetAnswer {
            get {
                object obj = ResourceManager.GetObject("ResetAnswer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap RightAnswer {
            get {
                object obj = ResourceManager.GetObject("RightAnswer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap RightAnswerCheck {
            get {
                object obj = ResourceManager.GetObject("RightAnswerCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap savefile {
            get {
                object obj = ResourceManager.GetObject("savefile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sheep1 {
            get {
                object obj = ResourceManager.GetObject("sheep1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sheep2 {
            get {
                object obj = ResourceManager.GetObject("sheep2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sheep3 {
            get {
                object obj = ResourceManager.GetObject("sheep3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sheep4 {
            get {
                object obj = ResourceManager.GetObject("sheep4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap sheep5 {
            get {
                object obj = ResourceManager.GetObject("sheep5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SheepLogo {
            get {
                object obj = ResourceManager.GetObject("SheepLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
